apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vswf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vswf
    app.kubernetes.io/part-of: byoc-app-pqhx
  name: vswf
spec:
  rules:
  - host: vswf-byoc-gfes-tenant.apps.0c0dd28e810f0887b6e7.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: vswf
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
